FROM node:12.5.0-alpine AS builder

WORKDIR /app
ADD package.json package.json
ADD yarn.lock yarn.lock

RUN yarn install

ADD . /app/

RUN yarn build


FROM node:12.5.0-alpine as packages

WORKDIR /app
ADD package.json package.json
ADD yarn.lock yarn.lock

RUN yarn install --production


FROM node:12.5.0-alpine

COPY --from=packages /app/node_modules /node_modules
COPY --from=builder /app/build /build
