version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    env_file:
      - react-dev.env
    command: yarn dev
