version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
      - $GOOGLE_APPLICATION_CREDENTIALS:/tmp/keys/GoogleCloudCredentials-codewayassignment-206450ebe987.json:ro
    env_file:
      - secret.env
    command: yarn dev
